### ISSUE TITLE
Gyro Update Rates

### ISSUE THREAD

**Issue by shmurthy7002** [Studica-Robotics/NavX#2]
**Is your feature request related to a problem? Please describe.**
My team is running a custom implementation of high frequency odometry with the NavX using the custom update rates, but the problem we are having right now is that the odometry thread which updates the gyro and swerve module positions is running at 100Hz and the main thread is running at 50Hz, this means sometimes the threads are trying to use the same resources at the same time since 100 is a multiple of 50. This causes various issues.

**Describe the solution you'd like**
I would like a feature where instead of selecting with the enum its possible to just pick a number from 0-200 or have more options inside the enum, this way I can pick a number that is not a multiple of 50, such as 125 or 175.

**Describe alternatives you've considered**
The alternative is to keep track of the threads in code and use async programming but because of the way our codebase is structured this turns out to be very difficult. It is also slower because threads would have to wait on each other constantly.

Thanks in advance

**Comment by Jm-Taylor** [comment]
This is something I can re-add. Just note that if you pick a value outside of what the enums are the actual update rate will be different. But can be checked with:
```java
getActualUpdateRate()
```

**Comment by shmurthy7002** [comment]
Ok, thanks

**Comment by Jm-Taylor** [comment]
I rolled out an alpha version for you to use and test. 
```
https://dev.studica.com/releases/2025/Studica-2025.1.1-alpha-10.json
```

**Comment by shmurthy7002** [comment]
Awesome, I'll try it out

**Comment by Jm-Taylor** [comment]
Added to Beta 4 Release
