### ISSUE TITLE
Sim under 2025 beta not working

### ISSUE THREAD

**Issue by Crossle86** [Studica-Robotics/NavX#3]
My code does the following for NavX simulation:

    if (RobotBase.isSimulation())
    {
      var dev = SimDeviceDataJNI.getSimDeviceHandle("navX-Sensor[0]");

      simAngle = new SimDouble((SimDeviceDataJNI.getSimValueHandle(dev, "Yaw")));
    }

Then manipulate simAngle. Worked until install of 2025 vendordep. Now NavX angle does not change during sim. Is this still correct?

I have not yet installed the Windows binary. Is that needed to use the AHRS class in code?

**Comment by Jm-Taylor** [comment]
We are re-writing / fixing some things with the simulation. 

Your code would still work however requires one small change currently. 

```java
if (RobotBase.isSimulation())
{
  var dev = SimDeviceDataJNI.getSimDeviceHandle("navX-Sensor[port#]");

  simAngle = new SimDouble((SimDeviceDataJNI.getSimValueHandle(dev, "Yaw")));
}
```

**port#** would need to change to one of the following:

```java
4    // kMXP
1    // kMXP_UART
2    // kUSB1
3    // kUSB2
1    // kMXP_I2C
```

When we finish with the latest changes the API would look like this:

```java
// imports
private AHRS navx;
private SimDeviceSim device;
private SimDouble simAngle;

// inside constructor
navx = new AHRS(AHRS.NavXComType.kMXP_SPI); 
device = new SimDeviceSim("navX-Sensor", navx.getPort());
simAngle = device.getDouble("Yaw");
```

Thus with multiple navxs on board the user would not need to know the port #.

Hope this helps.

**Comment by Crossle86** [comment]
Thanks, that worked.
