### ISSUE TITLE
Java crash on ahrs.getBoardYawAxis()

### ISSUE THREAD

**Issue by Crossle86** [Studica-Robotics/NavX#4]
I  am getting the following crash on  AHRS.BoardYawAxis yaw_axis = ahrs.getBoardYawAxis(); on beta 3d.
#
# A fatal error has been detected by the Java Runtime Environment:
<29>01:51:02:832: Lib.MonitorPDP.run(MonitorPDP.java:174)
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff82b73c9d0, pid=8408, tid=18768
#
# JRE version: OpenJDK Runtime Environment Temurin-17.0.12+7 (17.0.12+7) (build 17.0.12+7)
# Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.12+7 (17.0.12+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0xc9d0]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# [hs_err_pid8408.log](https://github.com/user-attachments/files/18102967/hs_err_pid8408.log)
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
PS C:\Users\rcorn\workspace\FRC Java\Robot25B>

**Comment by Jm-Taylor** [comment]
Thanks I'll check it out.

**Comment by Jm-Taylor** [comment]
Fixed in Beta 4 Release.
